const test = require('node:test');
const assert = require('node:assert/strict');
const request = require('supertest');
const { createDatabase } = require('../src/db');
const { createApp } = require('../src/server');

function setup() { const db = createDatabase(':memory:'); const instance = createApp({ db }); const agent = request.agent(instance.app); return { db, app: instance.app, agent }; }
async function csrf(agent) { const response = await agent.get('/api/me'); return response.headers['set-cookie'].find(value => value.startsWith('csrf_token=')).split(';')[0].split('=')[1]; }
function body(agent, method, url, payload, csrfToken) { return agent[method](url).set('x-csrf-token', csrfToken).send(payload); }

test('rejects weak passwords and registers a strong password', async () => { const { agent, db } = setup(); const csrfToken = await csrf(agent); const weak = await body(agent, 'post', '/api/register', { email: 'a@example.com', displayName: 'A', password: 'password123' }, csrfToken); assert.equal(weak.status, 400); const good = await body(agent, 'post', '/api/register', { email: 'a@example.com', displayName: 'A', password: 'BetterPassword9!' }, csrfToken); assert.equal(good.status, 201); assert.match(db.prepare('SELECT password_hash FROM users').get().password_hash, /^\$argon2id\$/); });
test('logs in, protects routes, creates a session, and logs out', async () => { const { agent, db } = setup(); let token = await csrf(agent); await body(agent, 'post', '/api/register', { email: 'b@example.com', displayName: 'B', password: 'BetterPassword9!' }, token); assert.equal((await agent.get('/api/sessions')).status, 200); assert.equal(db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n, 1); token = await csrf(agent); assert.equal((await body(agent, 'post', '/api/logout', {}, token)).status, 200); assert.equal((await agent.get('/api/sessions')).status, 401); });
test('rejects sessions past the inactivity window', async () => { const { agent, db } = setup(); let token = await csrf(agent); await body(agent, 'post', '/api/register', { email: 'idle@example.com', displayName: 'Idle', password: 'BetterPassword9!' }, token); db.prepare("UPDATE sessions SET last_active_at = datetime('now', '-2 hours')").run(); assert.equal((await agent.get('/api/sessions')).status, 401); });
test('incorrect credentials are generic and repeated failures are recorded', async () => { const { agent, db } = setup(); const token = await csrf(agent); for (let i = 0; i < 5; i++) { const response = await body(agent, 'post', '/api/login', { email: 'missing@example.com', password: 'wrong' }, token); assert.equal(response.status, 401); assert.equal(response.body.error, 'Unable to sign in with those details.'); } assert.ok(db.prepare("SELECT COUNT(*) AS n FROM security_events WHERE event_type = 'repeated_failed_login_attempts'").get().n >= 1); });
test('limits repeated login attempts from one IP across changing emails', async () => { const { agent } = setup(); const token = await csrf(agent); let response; for (let i = 0; i < 60; i++) response = await body(agent, 'post', '/api/login', { email: `user${i}@example.com`, password: 'wrong' }, token); assert.equal(response.status, 401); response = await body(agent, 'post', '/api/login', { email: 'different@example.com', password: 'wrong' }, token); assert.equal(response.status, 429); });
test('csrf protects state-changing requests and unauthenticated routes', async () => { const { app } = setup(); assert.equal((await request(app).post('/api/logout').send({})).status, 403); assert.equal((await request(app).get('/api/sessions')).status, 401); });
test('revokes an individual session and records suspicious new IP activity', async () => { const { agent, db } = setup(); let token = await csrf(agent); await body(agent, 'post', '/api/register', { email: 'c@example.com', displayName: 'C', password: 'BetterPassword9!' }, token); const second = request.agent((createApp({ db })).app); token = await csrf(second); await body(second, 'post', '/api/login', { email: 'c@example.com', password: 'BetterPassword9!' }, token); const sessions = await agent.get('/api/sessions'); assert.equal(sessions.body.sessions.length, 2); token = await csrf(agent); const revoke = await body(agent, 'delete', `/api/sessions/${sessions.body.sessions.find(session => !session.current).id}`, {}, token); assert.equal(revoke.status, 200); assert.equal(db.prepare("SELECT COUNT(*) AS n FROM security_events WHERE event_type = 'session_revoked'").get().n, 1); assert.ok(db.prepare("SELECT COUNT(*) AS n FROM security_events WHERE event_type = 'suspicious_login'").get().n >= 1); });
